### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by belingud** [Alfred1984/interesting-python#9]
遇到了 `json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)` 的错误，新手，没有解决

**Comment by Alfred1984** [comment]
哪个项目？

**Comment by belingud** [comment]
爬虫爬取微博表情包的项目，Weibo_Comment_Pics

**Comment by taopin** [comment]
需要在get_m_url()函数中加上utf8才能顺利执行起来，如下：
        headers = {'Cookie': cookie.encode('utf-8')}

然后我可以顺利抓取到第一页的数据和图片，但是到第二页就遇到了上面同样的JSONDecodeError错误，详情见下：
============ RESTART: C:\weibo\photo_clawler.py ============
对应的手机网页端id是：4333xxx50xxx4xxx
模拟登录手机网页端微博成功！
成功抓取第1页的图片链接！
Traceback (most recent call last):
  File "C:\weibo\photo_clawler.py", line 151, in <module>
    com.get_comments(max_page=20)
  File "C:\weibo\photo_clawler.py", line 91, in get_comments
    max_id = response.json()['data']['max_id']
  File "C:\Python\Python37\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Python\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
>>>

**Comment by liangzhongkai** [comment]
您的来信我已收到，谢谢
